### PR TITLE
updating the module to terraform 0.12

### PR DESCRIPTION
**Pull request by alexvaque**

### CODE REVIEW

**Comment by nicofuccella** [comment]
+1

**Comment by nekottyo** [comment]
+1

**Comment by tmknom** [comment]
Sorry for the very late reply.

And thank you so much for your contribution!

**Comment by tmknom** [comment]
Released Terraform v0.12 compatible version as v2.0.0 🚀 
Please see https://github.com/tmknom/terraform-aws-ecs-scheduled-task/releases/tag/2.0.0

Thanks!

**Pull request merged**
